name: Deployment

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2+

      - name: Run tests
        run: yarn b:test

  deploy:
    runs-on: [ubuntu-latest]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v2

      - name: Set app environment
        run: echo "NODE_ENV='production'" > .env

      - name: (YARN) Install dependencies
        run: yarn install

      - name: (YARN) build
        run: yarn m:build

      - name: move files out of build folder
        run: mv build/* ./

      - name: Tar files
        run: tar -czf dist.tar.gz node_modules controllers models public routes index.js server.js package.json

      - name: Copy dist.tar.gz to server via scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist.tar.gz
          remote: ${{ secrets.DEPLOY_PATH }}/dist.tar.gz
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Extract and cleanup on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            rm -rf node_modules controllers models public routes index.js server.js package.json
            tar -xf dist.tar.gz
            rm dist.tar.gz