name: Test

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: (YARN) Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn b:test
